export default {
  POSTS__REQUEST_GET_ALL: 'POSTS__REQUEST_GET_ALL',
  POSTS__SUCCESS_GET_ALL: 'POSTS__SUCCESS_GET_ALL',
  POSTS__ERROR_GET_ALL: 'POSTS__ERROR_GET_ALL',

  POSTS__REQUEST_GET_ONE: 'POSTS__REQUEST_GET_ONE',
  POSTS__SUCCESS_GET_ONE: 'POSTS__SUCCESS_GET_ONE',
  POSTS__ERROR_GET_ONE: 'POSTS__ERROR_GET_ONE',

  CASE_STUDIES__REQUEST_GET_ALL: 'CASE_STUDIES__REQUEST_GET_ALL',
  CASE_STUDIES__SUCCESS_GET_ALL: 'CASE_STUDIES__SUCCESS_GET_ALL',
  CASE_STUDIES__ERROR_GET_ALL: 'CASE_STUDIES__ERROR_GET_ALL',

  CASE_STUDIES__REQUEST_GET_ONE: 'CASE_STUDIES__REQUEST_GET_ONE',
  CASE_STUDIES__SUCCESS_GET_ONE: 'CASE_STUDIES__SUCCESS_GET_ONE',
  CASE_STUDIES__ERROR_GET_ONE: 'CASE_STUDIES__ERROR_GET_ONE',

  JOBS__REQUEST_GET_ALL: 'JOBS__REQUEST_GET_ALL',
  JOBS__SUCCESS_GET_ALL: 'JOBS__SUCCESS_GET_ALL',
  JOBS__ERROR_GET_ALL: 'JOBS__ERROR_GET_ALL',

  JOBS__REQUEST_GET_ONE: 'JOBS__REQUEST_GET_ONE',
  JOBS__SUCCESS_GET_ONE: 'JOBS__SUCCESS_GET_ONE',
  JOBS__ERROR_GET_ONE: 'JOBS__ERROR_GET_ONE',
}
