export default {
  CART__REQUEST_ADD_ITEM: 'CART__REQUEST_ADD_ITEM',
  CART__SUCCESS_ADD_ITEM: 'CART__SUCCESS_ADD_ITEM', 
  CART__ERROR_ADD_ITEM: 'CART__ERROR_ADD_ITEM',

  CART__REQUEST_UPDATE_ITEM: 'CART__REQUEST_UPDATE_ITEM',
  CART__SUCCESS_UPDATE_ITEM: 'CART__SUCCESS_UPDATE_ITEM', 
  CART__ERROR_UPDATE_ITEM: 'CART__ERROR_UPDATE_ITEM',

  CART__REQUEST_REMOVE_ITEM: 'CART__REQUEST_REMOVE_ITEM',
  CART__SUCCESS_REMOVE_ITEM: 'CART__SUCCESS_REMOVE_ITEM', 
  CART__ERROR_REMOVE_ITEM: 'CART__ERROR_REMOVE_ITEM',

  CART__REQUEST_CREATE_CART: 'CART__REQUEST_CREATE_CART',
  CART__SUCCESS_CREATE_CART: 'CART__SUCCESS_CREATE_CART',
  CART__ERROR_CREATE_CART: 'CART__ERROR_CREATE_CART',

  CART__REQUEST_GET_CART: 'CART__REQUEST_GET_CART',
  CART__SUCCESS_GET_CART: 'CART__SUCCESS_GET_CART',
  CART__ERROR_GET_CART: 'CART__ERROR_GET_CART',

  CART__REQUEST_UPDATE_CART: 'CART__REQUEST_UPDATE_CART',
  CART__SUCCESS_UPDATE_CART: 'CART__SUCCESS_UPDATE_CART',
  CART__ERROR_UPDATE_CART: 'CART__ERROR_UPDATE_CART',

  CART__REQUEST_INITIATE: 'CART__REQUEST_INITIATE',
  CART__SUCCESS_INITIATE: 'CART__SUCCESS_INITIATE',
  CART__ERROR_INITIATE: 'CART__ERROR_INITIATE',

  CART__REQUEST_UPDATE_CUSTOMER_ID: 'CART__REQUEST_UPDATE_CUSTOMER_ID',
  CART__SUCCESS_UPDATE_CUSTOMER_ID: 'CART__SUCCESS_UPDATE_CUSTOMER_ID',
  CART__ERROR_UPDATE_CUSTOMER_ID: 'CART__ERROR_UPDATE_CUSTOMER_ID',
}