export default {
  NAVIGATION_TOGGLE_MOBILE_MENU: 'NAVIGATION_TOGGLE_MOBILE_MENU',
  NAVIGATION_SET_TEAM_MEMBER_MODAL: 'NAVIGATION_SET_TEAM_MEMBER_MODAL',
  NAVIGATION_TOGGLE_LOGIN_MODAL: 'NAVIGATION_TOGGLE_LOGIN_MODAL',
  NAVIGATION_SET_FIXED_STATE: 'NAVIGATION_SET_FIXED_STATE',
}
