export default {
  NAVIGATION_TOGGLE_MOBILE_MENU: 'NAVIGATION_TOGGLE_MOBILE_MENU',
  NAVIGATION_SET_TEAM_MEMBER_MODAL: 'NAVIGATION_SET_TEAM_MEMBER_MODAL',
  NAVIGATION_TOGGLE_LOGIN_MODAL: 'NAVIGATION_TOGGLE_LOGIN_MODAL',
  NAVIGATION_SET_FIXED_STATE: 'NAVIGATION_SET_FIXED_STATE',

  NAVIGATION_REQUEST_OPEN_DRAWER: 'NAVIGATION_REQUEST_OPEN_DRAWER',
  NAVIGATION_SUCCESS_OPEN_DRAWER: 'NAVIGATION_SUCCESS_OPEN_DRAWER',
  NAVIGATION_ERROR_OPEN_DRAWER: 'NAVIGATION_ERROR_OPEN_DRAWER',

  NAVIGATION_REQUEST_CLOSE_DRAWER: 'NAVIGATION_REQUEST_CLOSE_DRAWER',
  NAVIGATION_SUCCESS_CLOSE_DRAWER: 'NAVIGATION_SUCCESS_CLOSE_DRAWER',
  NAVIGATION_ERROCLOSEEN_DRAWER: 'NAVIGATION_ERROR_CLOSE_DRAWER',
}

