export default {
  USER__SET_STORE: 'USER__SET_STORE',
  
  USER__REQUEST_CREATE_CUSTOMER: 'USER__REQUEST_CREATE_CUSTOMER',
  USER__SUCCESS_CREATE_CUSTOMER: 'USER__SUCCESS_CREATE_CUSTOMER',
  USER__ERROR_CREATE_CUSTOMER: 'USER__ERROR_CREATE_CUSTOMER',

  USER__REQUEST_GET_CUSTOMER: 'USER__REQUEST_GET_CUSTOMER',
  USER__SUCCESS_GET_CUSTOMER: 'USER__SUCCESS_GET_CUSTOMER',
  USER__ERROR_GET_CUSTOMER: 'USER__ERROR_GET_CUSTOMER',

  USER__REQUEST_LOGIN_CUSTOMER: 'USER__REQUEST_LOGIN_CUSTOMER',
  USER__SUCCESS_LOGIN_CUSTOMER: 'USER__SUCCESS_LOGIN_CUSTOMER',
  USER__ERROR_LOGIN_CUSTOMER: 'USER__ERROR_LOGIN_CUSTOMER',
}
